#!/bin/bash

echo "Lithic POC Setup Script"
echo "======================"
echo ""
echo "Prerequisites:"
echo "1. Docker Desktop must be running"
echo "2. Supabase CLI installed (npm install -g supabase)"
echo ""
echo "To set up the project:"
echo ""
echo "1. Start Supabase:"
echo "   npx supabase start"
echo ""
echo "2. Run database migrations:"
echo "   npx supabase db reset --db-url postgresql://postgres:postgres@localhost:54322/postgres"
echo ""
echo "3. Apply schema:"
echo "   psql postgresql://postgres:postgres@localhost:54322/postgres < src/config/database.sql"
echo ""
echo "4. Start the backend server:"
echo "   npm run dev"
echo ""
echo "The backend will run on http://localhost:3001"
echo "Supabase Studio will be available at http://localhost:54323"